### ISSUE TITLE
Error with scipy 1.3

### ISSUE THREAD

**Issue by rmjarvis** [JoeMcEwen/FAST-PT#4]
Scipy changed where they keep the factorial function in version 1.3, which breaks "import fastpt".

The following is with the latest fast-pt release: 3.0.0:
```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:07:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastpt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/fastpt/__init__.py", line 37, in <module>
    from .FASTPT import *
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/fastpt/FASTPT.py", line 49, in <module>
    from .IA_tt import IA_tt
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/fastpt/IA_tt.py", line 2, in <module>
    from .J_table import J_table 
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/fastpt/J_table.py", line 9, in <module>
    from .Wigner_symbols import three_j, six_j
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/fastpt/Wigner_symbols.py", line 18, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial'
>>> import scipy
>>> scipy.__version__
'1.3.2'
```

**Comment by jablazek** [comment]
resolved with a2b20f0
